# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basestation.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 775, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setObjectName("groupBox")
        self.panjang_lapangan = QtWidgets.QLineEdit(self.groupBox)
        self.panjang_lapangan.setGeometry(QtCore.QRect(20, 470, 51, 25))
        self.panjang_lapangan.setObjectName("panjang_lapangan")
        self.lebar_lapangan = QtWidgets.QLineEdit(self.groupBox)
        self.lebar_lapangan.setGeometry(QtCore.QRect(90, 470, 51, 25))
        self.lebar_lapangan.setObjectName("lebar_lapangan")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(8, 474, 16, 17))
        self.label.setObjectName("label")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(80, 474, 16, 17))
        self.label_18.setObjectName("label_18")
        self.refresh = QtWidgets.QPushButton(self.groupBox)
        self.refresh.setGeometry(QtCore.QRect(150, 470, 71, 25))
        self.refresh.setObjectName("refresh")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(350, 450, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.posmap_r1 = QtWidgets.QLabel(self.groupBox)
        self.posmap_r1.setGeometry(QtCore.QRect(370, 450, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_r1.setFont(font)
        self.posmap_r1.setObjectName("posmap_r1")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(350, 460, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.posmap_r2 = QtWidgets.QLabel(self.groupBox)
        self.posmap_r2.setGeometry(QtCore.QRect(370, 460, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_r2.setFont(font)
        self.posmap_r2.setObjectName("posmap_r2")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(350, 470, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.posmap_r3 = QtWidgets.QLabel(self.groupBox)
        self.posmap_r3.setGeometry(QtCore.QRect(370, 470, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_r3.setFont(font)
        self.posmap_r3.setObjectName("posmap_r3")
        self.check_invv = QtWidgets.QCheckBox(self.groupBox)
        self.check_invv.setGeometry(QtCore.QRect(230, 470, 61, 23))
        self.check_invv.setObjectName("check_invv")
        self.check_invh = QtWidgets.QCheckBox(self.groupBox)
        self.check_invh.setGeometry(QtCore.QRect(290, 470, 61, 23))
        self.check_invh.setObjectName("check_invh")
        self.posmap_b1 = QtWidgets.QLabel(self.groupBox)
        self.posmap_b1.setGeometry(QtCore.QRect(510, 450, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_b1.setFont(font)
        self.posmap_b1.setObjectName("posmap_b1")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(480, 450, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.posmap_b2 = QtWidgets.QLabel(self.groupBox)
        self.posmap_b2.setGeometry(QtCore.QRect(510, 460, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_b2.setFont(font)
        self.posmap_b2.setObjectName("posmap_b2")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(480, 460, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.posmap_b3 = QtWidgets.QLabel(self.groupBox)
        self.posmap_b3.setGeometry(QtCore.QRect(510, 470, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_b3.setFont(font)
        self.posmap_b3.setObjectName("posmap_b3")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(480, 470, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.posmap_rb = QtWidgets.QLabel(self.groupBox)
        self.posmap_rb.setGeometry(QtCore.QRect(510, 480, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_rb.setFont(font)
        self.posmap_rb.setObjectName("posmap_rb")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(480, 480, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.posmap_mouse = QtWidgets.QLabel(self.groupBox)
        self.posmap_mouse.setGeometry(QtCore.QRect(670, 480, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.posmap_mouse.setFont(font)
        self.posmap_mouse.setObjectName("posmap_mouse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 500, 410, 188))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(9, 130, 91, 17))
        self.label_8.setObjectName("label_8")
        self.override_r1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.override_r1.setGeometry(QtCore.QRect(10, 150, 141, 23))
        self.override_r1.setObjectName("override_r1")
        self.status_r1 = QtWidgets.QLabel(self.groupBox_2)
        self.status_r1.setGeometry(QtCore.QRect(110, 30, 81, 17))
        self.status_r1.setObjectName("status_r1")
        self.posisi_r1 = QtWidgets.QLabel(self.groupBox_2)
        self.posisi_r1.setGeometry(QtCore.QRect(110, 60, 121, 17))
        self.posisi_r1.setObjectName("posisi_r1")
        self.behavior_r1 = QtWidgets.QLabel(self.groupBox_2)
        self.behavior_r1.setGeometry(QtCore.QRect(100, 130, 301, 17))
        self.behavior_r1.setObjectName("behavior_r1")
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(243, 30, 51, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(38, 110, 51, 17))
        self.label_24.setObjectName("label_24")
        self.role_r1 = QtWidgets.QComboBox(self.groupBox_2)
        self.role_r1.setGeometry(QtCore.QRect(302, 28, 101, 25))
        self.role_r1.setObjectName("role_r1")
        self.role_r1.addItem("")
        self.role_r1.addItem("")
        self.role_r1.addItem("")
        self.role_r1.addItem("")
        self.command_r1 = QtWidgets.QLabel(self.groupBox_2)
        self.command_r1.setGeometry(QtCore.QRect(100, 110, 301, 17))
        self.command_r1.setObjectName("command_r1")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(226, 60, 70, 17))
        self.label_35.setObjectName("label_35")
        self.posreal_r1 = QtWidgets.QLabel(self.groupBox_2)
        self.posreal_r1.setGeometry(QtCore.QRect(300, 60, 101, 17))
        self.posreal_r1.setObjectName("posreal_r1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(800, 0, 480, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.groupBox_5.setPalette(palette)
        self.groupBox_5.setMouseTracking(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(10, 400, 111, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(10, 430, 111, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(10, 460, 111, 17))
        self.label_4.setObjectName("label_4")
        self.menyerang = QtWidgets.QComboBox(self.groupBox_5)
        self.menyerang.setGeometry(QtCore.QRect(130, 400, 121, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        self.menyerang.setPalette(palette)
        self.menyerang.setObjectName("menyerang")
        self.menyerang.addItem("")
        self.menyerang.addItem("")
        self.menyerang.addItem("")
        self.tim = QtWidgets.QComboBox(self.groupBox_5)
        self.tim.setGeometry(QtCore.QRect(130, 460, 121, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.tim.setPalette(palette)
        self.tim.setObjectName("tim")
        self.tim.addItem("")
        self.tim.addItem("")
        self.goal_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.goal_cyan.setGeometry(QtCore.QRect(10, 86, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.goal_cyan.setPalette(palette)
        self.goal_cyan.setObjectName("goal_cyan")
        self.kickoff_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.kickoff_cyan.setGeometry(QtCore.QRect(110, 86, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.kickoff_cyan.setPalette(palette)
        self.kickoff_cyan.setObjectName("kickoff_cyan")
        self.freekick_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.freekick_cyan.setGeometry(QtCore.QRect(110, 116, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.freekick_cyan.setPalette(palette)
        self.freekick_cyan.setObjectName("freekick_cyan")
        self.goalkick_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.goalkick_cyan.setGeometry(QtCore.QRect(110, 146, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.goalkick_cyan.setPalette(palette)
        self.goalkick_cyan.setObjectName("goalkick_cyan")
        self.throwin_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.throwin_cyan.setGeometry(QtCore.QRect(110, 176, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.throwin_cyan.setPalette(palette)
        self.throwin_cyan.setObjectName("throwin_cyan")
        self.corner_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.corner_cyan.setGeometry(QtCore.QRect(110, 206, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.corner_cyan.setPalette(palette)
        self.corner_cyan.setObjectName("corner_cyan")
        self.penalty_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.penalty_cyan.setGeometry(QtCore.QRect(110, 236, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.penalty_cyan.setPalette(palette)
        self.penalty_cyan.setObjectName("penalty_cyan")
        self.repair_cyan = QtWidgets.QPushButton(self.groupBox_5)
        self.repair_cyan.setGeometry(QtCore.QRect(10, 236, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.repair_cyan.setPalette(palette)
        self.repair_cyan.setObjectName("repair_cyan")
        self.goal_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.goal_magenta.setGeometry(QtCore.QRect(380, 86, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.goal_magenta.setPalette(palette)
        self.goal_magenta.setObjectName("goal_magenta")
        self.kickoff_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.kickoff_magenta.setGeometry(QtCore.QRect(280, 86, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.kickoff_magenta.setPalette(palette)
        self.kickoff_magenta.setObjectName("kickoff_magenta")
        self.freekick_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.freekick_magenta.setGeometry(QtCore.QRect(280, 116, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.freekick_magenta.setPalette(palette)
        self.freekick_magenta.setObjectName("freekick_magenta")
        self.goalkick_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.goalkick_magenta.setGeometry(QtCore.QRect(280, 146, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.goalkick_magenta.setPalette(palette)
        self.goalkick_magenta.setObjectName("goalkick_magenta")
        self.throwin_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.throwin_magenta.setGeometry(QtCore.QRect(280, 176, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.throwin_magenta.setPalette(palette)
        self.throwin_magenta.setObjectName("throwin_magenta")
        self.corner_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.corner_magenta.setGeometry(QtCore.QRect(280, 206, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.corner_magenta.setPalette(palette)
        self.corner_magenta.setObjectName("corner_magenta")
        self.penalty_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.penalty_magenta.setGeometry(QtCore.QRect(280, 236, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.penalty_magenta.setPalette(palette)
        self.penalty_magenta.setObjectName("penalty_magenta")
        self.repair_magenta = QtWidgets.QPushButton(self.groupBox_5)
        self.repair_magenta.setGeometry(QtCore.QRect(380, 236, 89, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.repair_magenta.setPalette(palette)
        self.repair_magenta.setObjectName("repair_magenta")
        self.start = QtWidgets.QPushButton(self.groupBox_5)
        self.start.setGeometry(QtCore.QRect(210, 86, 60, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.start.setPalette(palette)
        self.start.setObjectName("start")
        self.drop = QtWidgets.QPushButton(self.groupBox_5)
        self.drop.setGeometry(QtCore.QRect(210, 146, 60, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 127, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.drop.setPalette(palette)
        self.drop.setObjectName("drop")
        self.end = QtWidgets.QPushButton(self.groupBox_5)
        self.end.setGeometry(QtCore.QRect(210, 236, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.end.setPalette(palette)
        self.end.setObjectName("end")
        self.stop = QtWidgets.QPushButton(self.groupBox_5)
        self.stop.setGeometry(QtCore.QRect(210, 116, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.stop.setPalette(palette)
        self.stop.setObjectName("stop")
        self.park = QtWidgets.QPushButton(self.groupBox_5)
        self.park.setGeometry(QtCore.QRect(210, 176, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(237, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.park.setPalette(palette)
        self.park.setObjectName("park")
        self.reset = QtWidgets.QPushButton(self.groupBox_5)
        self.reset.setGeometry(QtCore.QRect(210, 206, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.reset.setPalette(palette)
        self.reset.setObjectName("reset")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 25, 31, 31))
        self.label_17.setObjectName("label_17")
        self.connecting = QtWidgets.QPushButton(self.groupBox_5)
        self.connecting.setGeometry(QtCore.QRect(331, 30, 89, 25))
        self.connecting.setObjectName("connecting")
        self.ip = QtWidgets.QLineEdit(self.groupBox_5)
        self.ip.setGeometry(QtCore.QRect(30, 30, 113, 25))
        self.ip.setObjectName("ip")
        self.bertahan = QtWidgets.QComboBox(self.groupBox_5)
        self.bertahan.setGeometry(QtCore.QRect(130, 430, 121, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bertahan.setPalette(palette)
        self.bertahan.setObjectName("bertahan")
        self.bertahan.addItem("")
        self.bertahan.addItem("")
        self.bertahan.addItem("")
        self.refbox = QtWidgets.QCheckBox(self.groupBox_5)
        self.refbox.setGeometry(QtCore.QRect(10, 59, 81, 23))
        self.refbox.setObjectName("refbox")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(100, 61, 51, 17))
        self.label_19.setObjectName("label_19")
        self.state = QtWidgets.QLabel(self.groupBox_5)
        self.state.setGeometry(QtCore.QRect(150, 60, 271, 17))
        self.state.setObjectName("state")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(160, 35, 41, 17))
        self.label_29.setObjectName("label_29")
        self.port = QtWidgets.QLineEdit(self.groupBox_5)
        self.port.setGeometry(QtCore.QRect(207, 30, 113, 25))
        self.port.setObjectName("port")
        self.label_34 = QtWidgets.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(10, 370, 111, 17))
        self.label_34.setObjectName("label_34")
        self.command = QtWidgets.QLabel(self.groupBox_5)
        self.command.setGeometry(QtCore.QRect(130, 370, 111, 17))
        self.command.setObjectName("command")
        self.btn_saveSerang = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_saveSerang.setGeometry(QtCore.QRect(260, 400, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.btn_saveSerang.setPalette(palette)
        self.btn_saveSerang.setObjectName("btn_saveSerang")
        self.btn_saveBertahan = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_saveBertahan.setGeometry(QtCore.QRect(260, 430, 61, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.btn_saveBertahan.setPalette(palette)
        self.btn_saveBertahan.setObjectName("btn_saveBertahan")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 500, 410, 188))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.label_12.setObjectName("label_12")
        self.override_r2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.override_r2.setGeometry(QtCore.QRect(10, 150, 141, 23))
        self.override_r2.setObjectName("override_r2")
        self.status_r2 = QtWidgets.QLabel(self.groupBox_3)
        self.status_r2.setGeometry(QtCore.QRect(100, 30, 81, 17))
        self.status_r2.setObjectName("status_r2")
        self.posisi_r2 = QtWidgets.QLabel(self.groupBox_3)
        self.posisi_r2.setGeometry(QtCore.QRect(100, 60, 131, 17))
        self.posisi_r2.setObjectName("posisi_r2")
        self.behavior_r2 = QtWidgets.QLabel(self.groupBox_3)
        self.behavior_r2.setGeometry(QtCore.QRect(100, 130, 301, 17))
        self.behavior_r2.setObjectName("behavior_r2")
        self.role_r2 = QtWidgets.QComboBox(self.groupBox_3)
        self.role_r2.setGeometry(QtCore.QRect(301, 29, 101, 25))
        self.role_r2.setObjectName("role_r2")
        self.role_r2.addItem("")
        self.role_r2.addItem("")
        self.role_r2.addItem("")
        self.role_r2.addItem("")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(242, 31, 51, 17))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(39, 111, 51, 17))
        self.label_26.setObjectName("label_26")
        self.command_r2 = QtWidgets.QLabel(self.groupBox_3)
        self.command_r2.setGeometry(QtCore.QRect(99, 111, 301, 17))
        self.command_r2.setObjectName("command_r2")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(226, 61, 70, 17))
        self.label_36.setObjectName("label_36")
        self.posreal_r2 = QtWidgets.QLabel(self.groupBox_3)
        self.posreal_r2.setGeometry(QtCore.QRect(300, 61, 101, 17))
        self.posreal_r2.setObjectName("posreal_r2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(860, 500, 410, 188))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_4.setPalette(palette)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.label_16.setObjectName("label_16")
        self.override_r3 = QtWidgets.QCheckBox(self.groupBox_4)
        self.override_r3.setGeometry(QtCore.QRect(10, 150, 141, 23))
        self.override_r3.setObjectName("override_r3")
        self.status_r3 = QtWidgets.QLabel(self.groupBox_4)
        self.status_r3.setGeometry(QtCore.QRect(100, 30, 81, 17))
        self.status_r3.setObjectName("status_r3")
        self.posisi_r3 = QtWidgets.QLabel(self.groupBox_4)
        self.posisi_r3.setGeometry(QtCore.QRect(100, 60, 131, 17))
        self.posisi_r3.setObjectName("posisi_r3")
        self.behavior_r3 = QtWidgets.QLabel(self.groupBox_4)
        self.behavior_r3.setGeometry(QtCore.QRect(100, 130, 301, 17))
        self.behavior_r3.setObjectName("behavior_r3")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_5.setGeometry(QtCore.QRect(301, 30, 101, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(242, 32, 51, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(39, 112, 51, 17))
        self.label_28.setObjectName("label_28")
        self.command_r3 = QtWidgets.QLabel(self.groupBox_4)
        self.command_r3.setGeometry(QtCore.QRect(99, 112, 301, 17))
        self.command_r3.setObjectName("command_r3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(226, 62, 70, 17))
        self.label_37.setObjectName("label_37")
        self.posreal_r3 = QtWidgets.QLabel(self.groupBox_4)
        self.posreal_r3.setGeometry(QtCore.QRect(300, 62, 101, 17))
        self.posreal_r3.setObjectName("posreal_r3")
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.refbox.clicked['bool'].connect(self.kickoff_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.freekick_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.goalkick_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.throwin_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.corner_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.penalty_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.repair_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.goal_magenta.setDisabled)
        self.refbox.clicked['bool'].connect(self.stop.setDisabled)
        self.refbox.clicked['bool'].connect(self.park.setDisabled)
        self.refbox.clicked['bool'].connect(self.reset.setDisabled)
        self.refbox.clicked['bool'].connect(self.goal_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.kickoff_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.freekick_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.goalkick_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.throwin_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.corner_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.penalty_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.repair_cyan.setDisabled)
        self.refbox.clicked['bool'].connect(self.start.setDisabled)
        self.refbox.clicked['bool'].connect(self.drop.setDisabled)
        self.refbox.clicked['bool'].connect(self.end.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Lapangan"))
        self.panjang_lapangan.setText(_translate("MainWindow", "900"))
        self.lebar_lapangan.setText(_translate("MainWindow", "600"))
        self.label.setText(_translate("MainWindow", "P"))
        self.label_18.setText(_translate("MainWindow", "L"))
        self.refresh.setText(_translate("MainWindow", "REFRESH"))
        self.label_20.setText(_translate("MainWindow", "R1 :"))
        self.posmap_r1.setText(_translate("MainWindow", "0,0"))
        self.label_22.setText(_translate("MainWindow", "R2 :"))
        self.posmap_r2.setText(_translate("MainWindow", "0,0"))
        self.label_31.setText(_translate("MainWindow", "R3 :"))
        self.posmap_r3.setText(_translate("MainWindow", "0,0"))
        self.check_invv.setText(_translate("MainWindow", "Inv V"))
        self.check_invh.setText(_translate("MainWindow", "Inv H"))
        self.posmap_b1.setText(_translate("MainWindow", "0,0"))
        self.label_21.setText(_translate("MainWindow", "B1 :"))
        self.posmap_b2.setText(_translate("MainWindow", "0,0"))
        self.label_30.setText(_translate("MainWindow", "B2 :"))
        self.posmap_b3.setText(_translate("MainWindow", "0,0"))
        self.label_32.setText(_translate("MainWindow", "B3 :"))
        self.posmap_rb.setText(_translate("MainWindow", "0,0"))
        self.label_33.setText(_translate("MainWindow", "RB :"))
        self.posmap_mouse.setText(_translate("MainWindow", "0,0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Robot 1"))
        self.label_5.setText(_translate("MainWindow", "STATUS       :"))
        self.label_6.setText(_translate("MainWindow", "POSISI         :"))
        self.label_8.setText(_translate("MainWindow", "BEHAVIOR :"))
        self.override_r1.setText(_translate("MainWindow", "OVERRIDE Ctrl+1"))
        self.status_r1.setText(_translate("MainWindow", "Disconnect"))
        self.posisi_r1.setText(_translate("MainWindow", "0,0"))
        self.behavior_r1.setText(_translate("MainWindow", "-"))
        self.label_23.setText(_translate("MainWindow", "ROLE  :"))
        self.label_24.setText(_translate("MainWindow", "CMND :"))
        self.role_r1.setItemText(0, _translate("MainWindow", "No Life"))
        self.role_r1.setItemText(1, _translate("MainWindow", "Striker"))
        self.role_r1.setItemText(2, _translate("MainWindow", "Middle"))
        self.role_r1.setItemText(3, _translate("MainWindow", "Keeper"))
        self.command_r1.setText(_translate("MainWindow", "-"))
        self.label_35.setText(_translate("MainWindow", "POSReal :"))
        self.posreal_r1.setText(_translate("MainWindow", "-"))
        self.groupBox_5.setTitle(_translate("MainWindow", "RefBox"))
        self.label_2.setText(_translate("MainWindow", "MENYERANG"))
        self.label_3.setText(_translate("MainWindow", "BERTAHAN"))
        self.label_4.setText(_translate("MainWindow", "TIM"))
        self.menyerang.setItemText(0, _translate("MainWindow", "PLAN A"))
        self.menyerang.setItemText(1, _translate("MainWindow", "PLAN B"))
        self.menyerang.setItemText(2, _translate("MainWindow", "PLAN C"))
        self.tim.setItemText(0, _translate("MainWindow", "MAGENTA"))
        self.tim.setItemText(1, _translate("MainWindow", "CYAN"))
        self.goal_cyan.setText(_translate("MainWindow", "GOAL"))
        self.kickoff_cyan.setText(_translate("MainWindow", "KICKOFF"))
        self.freekick_cyan.setText(_translate("MainWindow", "FREEKICK"))
        self.goalkick_cyan.setText(_translate("MainWindow", "GOALKICK"))
        self.throwin_cyan.setText(_translate("MainWindow", "THROW IN"))
        self.corner_cyan.setText(_translate("MainWindow", "CORNER"))
        self.penalty_cyan.setText(_translate("MainWindow", "PENALTY"))
        self.repair_cyan.setText(_translate("MainWindow", "REPAIR"))
        self.goal_magenta.setText(_translate("MainWindow", "GOAL"))
        self.kickoff_magenta.setText(_translate("MainWindow", "KICKOFF"))
        self.freekick_magenta.setText(_translate("MainWindow", "FREEKICK"))
        self.goalkick_magenta.setText(_translate("MainWindow", "GOALKICK"))
        self.throwin_magenta.setText(_translate("MainWindow", "THROW IN"))
        self.corner_magenta.setText(_translate("MainWindow", "CORNER"))
        self.penalty_magenta.setText(_translate("MainWindow", "PENALTY"))
        self.repair_magenta.setText(_translate("MainWindow", "REPAIR"))
        self.start.setText(_translate("MainWindow", "START"))
        self.drop.setText(_translate("MainWindow", "DROP"))
        self.end.setText(_translate("MainWindow", "END"))
        self.stop.setText(_translate("MainWindow", "STOP"))
        self.park.setText(_translate("MainWindow", "PARK"))
        self.reset.setText(_translate("MainWindow", "RESET"))
        self.label_17.setText(_translate("MainWindow", "IP"))
        self.connecting.setText(_translate("MainWindow", "CONNECT"))
        self.ip.setText(_translate("MainWindow", "127.0.0.1"))
        self.bertahan.setItemText(0, _translate("MainWindow", "BERTAHAN 1"))
        self.bertahan.setItemText(1, _translate("MainWindow", "BERTAHAN 2"))
        self.bertahan.setItemText(2, _translate("MainWindow", "BERTAHAN 3"))
        self.refbox.setText(_translate("MainWindow", "REFBOX"))
        self.label_19.setText(_translate("MainWindow", "State :"))
        self.state.setText(_translate("MainWindow", "-"))
        self.label_29.setText(_translate("MainWindow", "PORT"))
        self.port.setText(_translate("MainWindow", "28097"))
        self.label_34.setText(_translate("MainWindow", "STATUS"))
        self.command.setText(_translate("MainWindow", "-"))
        self.btn_saveSerang.setText(_translate("MainWindow", "Save"))
        self.btn_saveBertahan.setText(_translate("MainWindow", "Save"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Robot 2"))
        self.label_9.setText(_translate("MainWindow", "STATUS       :"))
        self.label_10.setText(_translate("MainWindow", "POSISI         :"))
        self.label_12.setText(_translate("MainWindow", "BEHAVIOR :"))
        self.override_r2.setText(_translate("MainWindow", "OVERRIDE Ctrl+2"))
        self.status_r2.setText(_translate("MainWindow", "Disconnect"))
        self.posisi_r2.setText(_translate("MainWindow", "0,0"))
        self.behavior_r2.setText(_translate("MainWindow", "-"))
        self.role_r2.setItemText(0, _translate("MainWindow", "No Life"))
        self.role_r2.setItemText(1, _translate("MainWindow", "Striker"))
        self.role_r2.setItemText(2, _translate("MainWindow", "Middle"))
        self.role_r2.setItemText(3, _translate("MainWindow", "Keeper"))
        self.label_25.setText(_translate("MainWindow", "ROLE  :"))
        self.label_26.setText(_translate("MainWindow", "CMND :"))
        self.command_r2.setText(_translate("MainWindow", "-"))
        self.label_36.setText(_translate("MainWindow", "POSReal :"))
        self.posreal_r2.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Robot 3"))
        self.label_13.setText(_translate("MainWindow", "STATUS       :"))
        self.label_14.setText(_translate("MainWindow", "POSISI         :"))
        self.label_16.setText(_translate("MainWindow", "BEHAVIOR :"))
        self.override_r3.setText(_translate("MainWindow", "OVERRIDE Ctrl+3"))
        self.status_r3.setText(_translate("MainWindow", "Disconnect"))
        self.posisi_r3.setText(_translate("MainWindow", "0,0"))
        self.behavior_r3.setText(_translate("MainWindow", "-"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "No Life"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Striker"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Middle"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Keeper"))
        self.label_27.setText(_translate("MainWindow", "ROLE  :"))
        self.label_28.setText(_translate("MainWindow", "CMND :"))
        self.command_r3.setText(_translate("MainWindow", "-"))
        self.label_37.setText(_translate("MainWindow", "POSReal :"))
        self.posreal_r3.setText(_translate("MainWindow", "-"))
